### ISSUE TITLE
Caught exception from No Fist

### ISSUE THREAD

**Issue by rckymtnrfc** [whichonespink44/NoFist#5]
I'm getting a crash with No Fist installed on 1.12.  https://pastebin.com/HNypyNZ0

I'm using Forge 2406

**Comment by XvSkItZvX** [comment]
I seem to be having the same problem loading with this mod installed.
MC: 1.12
Forge: 2443
NoFist: 6.1.0.1

**Comment by whichonespink44** [comment]
This is likely because NoFist was built against Forge 14.21.0.2322... I'll try to update it to the latest 1.12 Forge soon.

**Comment by XvSkItZvX** [comment]
Awesome, thank you for your efforts, quick response, an contribution to the community. I do appreciate it.

**Comment by rckymtnrfc** [comment]
That would be amazing.  I'm using Tool Progression to prevent punching wood but I much preferred using No Fist.  Thanks for your time!

**Comment by Magi1053** [comment]
Any update on this fix?

**Comment by whichonespink44** [comment]
I'll be looking at this today.

**Comment by whichonespink44** [comment]
Fixed in c85abe3

New release available here:
https://minecraft.curseforge.com/projects/no-fist/files/2480760

**Comment by XvSkItZvX** [comment]
thank you.
